apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parking-app
  template:
    metadata:
      labels:
        app: parking-app
    spec:
      containers:
        - name: parking-container
          image: smart-parking-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501